add resful proxy
AerysNan/NaiveOSS pull request #3
Opened 2019-10-20 09:12 UTC by LebronAl

2019-10-28 05:54 UTC, AerysNan requested changes

2019-10-28 05:54 UTC, AerysNan commented on .gitignore
> +.idea
把 .idea 添加到全局的 .gitingore 中
https://help.github.com/cn/github/using-git/ignoring-files
不要添加在项目文件的 .gitignore 中

2019-10-28 05:54 UTC, AerysNan commented on cmd/client/main.go
> +	client        = kingpin.New("oss", "OSS Client")
main 中使用的还是 flag.Parse?

2019-10-28 05:54 UTC, AerysNan commented on metadata/bucket.go
> +	v := make(map[int64]int, 0)
只用到 key 的话: make(map[int64]struct{})
map 不必指定 size

2019-10-28 05:54 UTC, AerysNan commented on proxy/handler.go
> +	s.m.Unlock()
函数在此前 return 会导致死锁, 在加锁后用 defer  s.m.Unlock()

2019-10-28 05:54 UTC, AerysNan commented on storage/handler.go
> +	s.m.RUnlock()
.

2019-10-28 05:54 UTC, AerysNan commented on storage/handler.go
> +	s.m.Unlock()
.

2019-10-28 07:47 UTC, LebronAl commented on cmd/client/main.go
> +	client        = kingpin.New("oss", "OSS Client")
实际在build的时候用了kingpin的parse了，main函数里面删了flag.parse即可

2019-10-28 07:50 UTC, LebronAl commented on proxy/handler.go
> +	s.m.Unlock()
还是写两处unlock吧。因为之后的grpc请求实际并不需要加锁，meta的锁粒度能小则小吧

2019-10-29 17:26 UTC, OneSizeFitsQuorum commented on metadata/handler.go
> +			for _, v := range s.TagMap {
感觉这里设计有问题，如果对一个已存在的key覆盖put一个摘要已经存在在tagmap里但不是此key原本对应内容摘要的文件，那么此处在不维护key2tag的map情况下只能遍历tagmap来维护tapmap的一致性（即每一个key只出现在一个摘要对应的set里面）。由于tagmap的内容主要是对put和delete受影响，而put时即使冗余也没事，所以也可以惰性维护，即delete的时候判断一下当前tag对应的set里面每个item是否有效，但是这样gc的时候也得判断，感觉是个tradeoff，要是不改tagmap和memomap的结构我暂时没想到什么好的办法...

2019-10-29 17:27 UTC, OneSizeFitsQuorum commented on metadata/handler.go
> +	// for _, item := range set.Values() {
.

2019-10-30 11:08 UTC, AerysNan approved these changes

2019-10-30 11:20 UTC, AerysNan commented
LGTM

2019-10-30 11:20 UTC, merged